os:
  - linux
  - osx

language: python

python:
  - python: "2.7"
  - python: "3.5"
  - python: "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  # Beautify to PEP8
  - autopep8 --in-place --aggressive --aggressive telepy/telepy.py
  
  # Coverage
  - coverage run telepy/telepy.py
  - coverage xml
  - export CODACY_PROJECT_TOKEN=${CODACY_PROJECT_TOKEN}
  - python-codacy-coverage -r coverage.xml

  # Tests
  - pytest
notifications:
  email: false