sudo: False

language: python

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  - python setup.py install

script:
  - py.test --doctest-modules telepy

notifications:
  email: false